In [7]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv("data/players.csv")

Exploratory Data Analysis

In [4]:
df.shape

(25, 11)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   player_id        25 non-null     int64
 1   name             25 non-null     str
 2   position         25 non-null     str
 3   age              25 non-null     int64
 4   team             25 non-null     str
 5   games_played     25 non-null     int64
 6   minutes          25 non-null     int64
 7   points           25 non-null     int64
 8   assists          25 non-null     int64
 9   personal_fouls   25 non-null     int64
 10  technical_fouls  25 non-null     int64
dtypes: int64(8), str(3)
memory usage: 2.8 KB

In [10]:
df.describe()

,player_id,age,games_played,minutes,points,assists,personal_fouls,technical_fouls
count,25.000000,25.000000,25.000000,25.000000,25.000000,25.00000,25.000000,25.000000
mean,13.000000,27.120000,25.320000,711.040000,300.640000,81.88000,71.760000,0.640000
std,7.359801,3.609247,5.014313,237.288938,125.877877,52.22493,36.298852,0.860233
min,1.000000,20.000000,11.000000,154.000000,60.000000,15.00000,14.000000,0.000000
25%,7.000000,25.000000,24.000000,660.000000,230.000000,35.00000,52.000000,0.000000
50%,13.000000,27.000000,27.000000,810.000000,315.000000,80.00000,64.000000,0.000000
75%,19.000000,30.000000,29.000000,870.000000,395.000000,120.00000,105.000000,1.000000
max,25.000000,33.000000,30.000000,960.000000,540.000000,196.00000,132.000000,3.000000

In [11]:
df.head(3)

,player_id,name,position,age,team,games_played,minutes,points,assists,personal_fouls,technical_fouls
0,1,Adeyemi,PG,24,Lagos Leopards,28,896,336,196,58,0
1,2,Okafor,SG,29,Lagos Leopards,30,960,540,120,64,1
2,3,Balogun,SF,26,Lagos Leopards,27,864,410,140,70,0

In [12]:
print(df.tail())

    player_id     name position  age           team  games_played  minutes  \
20         21   Peprah       PG   26  Kumasi Giants            19      342
21         22  Quansah       SG   21  Kumasi Giants            15      240
22         23   Rahman       SF   33  Kumasi Giants            11      154
23         24    Sowah       PF   28  Kumasi Giants            22      374
24         25   Tetteh        C   30  Kumasi Giants            24      384

    points  assists  personal_fouls  technical_fouls
20     120       90              22                0
21     120       30              16                0
22      60       18              14                0
23     150       25              55                0
24     140       15              60                1

In [13]:
print(df.columns)

Index(['player_id', 'name', 'position', 'age', 'team', 'games_played',
       'minutes', 'points', 'assists', 'personal_fouls', 'technical_fouls'],
      dtype='str')

In [14]:
#print(df.iloc[0])
print(df.iloc[0:5])

   player_id     name position  age            team  games_played  minutes  \
0          1  Adeyemi       PG   24  Lagos Leopards            28      896
1          2   Okafor       SG   29  Lagos Leopards            30      960
2          3  Balogun       SF   26  Lagos Leopards            27      864
3          4   Diallo       PF   31  Lagos Leopards            29      928
4          5    Nwosu        C   28  Lagos Leopards            30      900

   points  assists  personal_fouls  technical_fouls
0     336      196              58                0
1     540      120              64                1
2     410      140              70                0
3     380       60             112                2
4     340       40             128                1

In [15]:
print(df.loc[df["age"] == 24])

    player_id     name position  age            team  games_played  minutes  \
0           1  Adeyemi       PG   24  Lagos Leopards            28      896
13         14   Ikpeba       PF   24      Kano Kings            22      660

    points  assists  personal_fouls  technical_fouls
0      336      196              58                0
13     255       48              95                2

In [16]:
guards = df[df["position"].isin(["SG", "PG"])]
print(guards.shape)
print(guards.head(5))

(10, 11)
    player_id     name position  age            team  games_played  minutes  \
0           1  Adeyemi       PG   24  Lagos Leopards            28      896
1           2   Okafor       SG   29  Lagos Leopards            30      960
5           6    Owusu       PG   22      Accra Aces            25      700
6           7   Appiah       SG   27      Accra Aces            28      868
10         11     Eneh       PG   23      Kano Kings            24      672

    points  assists  personal_fouls  technical_fouls
0      336      196              58                0
1      540      120              64                1
5      245      175              45                0
6      460       90              58                0
10     230      168              42                0

In [17]:
df["points_plus_assists"] = df["points"] + df["assists"]
df["points_per_game"] = df["points"] / (df["minutes"] / 36)
df["minutes_per_game"] = df["minutes"] / df["games_played"]
df.head()

,player_id,name,position,age,team,games_played,minutes,points,assists,personal_fouls,technical_fouls,points_plus_assists,points_per_game,minutes_per_game
0,1,Adeyemi,PG,24,Lagos Leopards,28,896,336,196,58,0,532,13.500000,32.0
1,2,Okafor,SG,29,Lagos Leopards,30,960,540,120,64,1,660,20.250000,32.0
2,3,Balogun,SF,26,Lagos Leopards,27,864,410,140,70,0,550,17.083333,32.0
3,4,Diallo,PF,31,Lagos Leopards,29,928,380,60,112,2,440,14.741379,32.0
4,5,Nwosu,C,28,Lagos Leopards,30,900,340,40,128,1,380,13.600000,30.0

In [18]:
df.to_csv("players_updated.csv", index=False)
print("Saved.")

Saved.

In [19]:
df.to_csv("players_updated1.csv", index=True)
print("Saved.")

Saved.